version: '3'
services:
  web:
    build: ./
    ports:
     - "80:80"
    networks:
     - backend
    depends_on:
     - database
    environment:
     - DATABASE_URL=postgresql://postgres@database:5432/postgres
     # postgresql://[user[:password]@][netloc][:port][/dbname]
     # defaults ://postgres@database:5432/postgres <- username
  database:
    image: "postgres"
    networks:
     - backend
networks:
  backend: