from setuptools import setup
setup(
    name='WhatAClass',
    packages=['WhatAClass'],
    include_package_data=True,
    install_requires=[
        'flask',
        'flask-bcrypt',
        'bcrypt',
        'flask-login',
        'flask-sqlalchemy',
        'flask-wtf',
        'wtforms',
        'click',
        'itsdangerous',
        'jinja2',
        'click',
        'sqlalchemy',
        'werkzeug',
        'jinja2',
    ],
    setup_requires=[
        'pytest-runner',
    ],
    tests_require=[
        'pytest',
    ],
)