from distutils.core import setup

setup(
    name='WhatAClass',
    version='v0.0.1',
    packages=['venv.lib.python3.5.site-packages.pip', 'venv.lib.python3.5.site-packages.pip.req',
              'venv.lib.python3.5.site-packages.pip.vcs', 'venv.lib.python3.5.site-packages.pip.utils',
              'venv.lib.python3.5.site-packages.pip.compat', 'venv.lib.python3.5.site-packages.pip.models',
              'venv.lib.python3.5.site-packages.pip._vendor', 'venv.lib.python3.5.site-packages.pip._vendor.distlib',
              'venv.lib.python3.5.site-packages.pip._vendor.distlib._backport',
              'venv.lib.python3.5.site-packages.pip._vendor.colorama',
              'venv.lib.python3.5.site-packages.pip._vendor.html5lib',
              'venv.lib.python3.5.site-packages.pip._vendor.html5lib._trie',
              'venv.lib.python3.5.site-packages.pip._vendor.html5lib.filters',
              'venv.lib.python3.5.site-packages.pip._vendor.html5lib.treewalkers',
              'venv.lib.python3.5.site-packages.pip._vendor.html5lib.treeadapters',
              'venv.lib.python3.5.site-packages.pip._vendor.html5lib.treebuilders',
              'venv.lib.python3.5.site-packages.pip._vendor.lockfile',
              'venv.lib.python3.5.site-packages.pip._vendor.progress',
              'venv.lib.python3.5.site-packages.pip._vendor.requests',
              'venv.lib.python3.5.site-packages.pip._vendor.requests.packages',
              'venv.lib.python3.5.site-packages.pip._vendor.requests.packages.chardet',
              'venv.lib.python3.5.site-packages.pip._vendor.requests.packages.urllib3',
              'venv.lib.python3.5.site-packages.pip._vendor.requests.packages.urllib3.util',
              'venv.lib.python3.5.site-packages.pip._vendor.requests.packages.urllib3.contrib',
              'venv.lib.python3.5.site-packages.pip._vendor.requests.packages.urllib3.packages',
              'venv.lib.python3.5.site-packages.pip._vendor.requests.packages.urllib3.packages.ssl_match_hostname',
              'venv.lib.python3.5.site-packages.pip._vendor.packaging',
              'venv.lib.python3.5.site-packages.pip._vendor.cachecontrol',
              'venv.lib.python3.5.site-packages.pip._vendor.cachecontrol.caches',
              'venv.lib.python3.5.site-packages.pip._vendor.webencodings',
              'venv.lib.python3.5.site-packages.pip._vendor.pkg_resources',
              'venv.lib.python3.5.site-packages.pip.commands', 'venv.lib.python3.5.site-packages.pip.operations',
              'venv.lib.python3.5.site-packages.cffi', 'venv.lib.python3.5.site-packages.mako',
              'venv.lib.python3.5.site-packages.mako.ext', 'venv.lib.python3.5.site-packages.pytz',
              'venv.lib.python3.5.site-packages.babel', 'venv.lib.python3.5.site-packages.babel.messages',
              'venv.lib.python3.5.site-packages.babel.localtime', 'venv.lib.python3.5.site-packages.click',
              'venv.lib.python3.5.site-packages.flask', 'venv.lib.python3.5.site-packages.flask.ext',
              'venv.lib.python3.5.site-packages.bcrypt', 'venv.lib.python3.5.site-packages.jinja2',
              'venv.lib.python3.5.site-packages.sphinx', 'venv.lib.python3.5.site-packages.sphinx.ext',
              'venv.lib.python3.5.site-packages.sphinx.ext.napoleon',
              'venv.lib.python3.5.site-packages.sphinx.ext.autosummary', 'venv.lib.python3.5.site-packages.sphinx.util',
              'venv.lib.python3.5.site-packages.sphinx.locale', 'venv.lib.python3.5.site-packages.sphinx.pycode',
              'venv.lib.python3.5.site-packages.sphinx.pycode.pgen2', 'venv.lib.python3.5.site-packages.sphinx.search',
              'venv.lib.python3.5.site-packages.sphinx.domains', 'venv.lib.python3.5.site-packages.sphinx.writers',
              'venv.lib.python3.5.site-packages.sphinx.builders', 'venv.lib.python3.5.site-packages.sphinx.directives',
              'venv.lib.python3.5.site-packages.sphinx.transforms',
              'venv.lib.python3.5.site-packages.sphinx.websupport',
              'venv.lib.python3.5.site-packages.sphinx.websupport.search',
              'venv.lib.python3.5.site-packages.sphinx.websupport.storage',
              'venv.lib.python3.5.site-packages.sphinx.environment',
              'venv.lib.python3.5.site-packages.sphinx.environment.managers',
              'venv.lib.python3.5.site-packages.alembic', 'venv.lib.python3.5.site-packages.alembic.ddl',
              'venv.lib.python3.5.site-packages.alembic.util', 'venv.lib.python3.5.site-packages.alembic.script',
              'venv.lib.python3.5.site-packages.alembic.runtime', 'venv.lib.python3.5.site-packages.alembic.testing',
              'venv.lib.python3.5.site-packages.alembic.testing.plugin',
              'venv.lib.python3.5.site-packages.alembic.operations',
              'venv.lib.python3.5.site-packages.alembic.autogenerate', 'venv.lib.python3.5.site-packages.wtforms',
              'venv.lib.python3.5.site-packages.wtforms.ext', 'venv.lib.python3.5.site-packages.wtforms.ext.csrf',
              'venv.lib.python3.5.site-packages.wtforms.ext.i18n',
              'venv.lib.python3.5.site-packages.wtforms.ext.django',
              'venv.lib.python3.5.site-packages.wtforms.ext.django.templatetags',
              'venv.lib.python3.5.site-packages.wtforms.ext.dateutil',
              'venv.lib.python3.5.site-packages.wtforms.ext.appengine',
              'venv.lib.python3.5.site-packages.wtforms.ext.sqlalchemy',
              'venv.lib.python3.5.site-packages.wtforms.csrf', 'venv.lib.python3.5.site-packages.wtforms.fields',
              'venv.lib.python3.5.site-packages.wtforms.widgets', 'venv.lib.python3.5.site-packages.docutils',
              'venv.lib.python3.5.site-packages.docutils.utils', 'venv.lib.python3.5.site-packages.docutils.utils.math',
              'venv.lib.python3.5.site-packages.docutils.parsers',
              'venv.lib.python3.5.site-packages.docutils.parsers.rst',
              'venv.lib.python3.5.site-packages.docutils.parsers.rst.languages',
              'venv.lib.python3.5.site-packages.docutils.parsers.rst.directives',
              'venv.lib.python3.5.site-packages.docutils.readers', 'venv.lib.python3.5.site-packages.docutils.writers',
              'venv.lib.python3.5.site-packages.docutils.writers.xetex',
              'venv.lib.python3.5.site-packages.docutils.writers.latex2e',
              'venv.lib.python3.5.site-packages.docutils.writers.odf_odt',
              'venv.lib.python3.5.site-packages.docutils.writers.s5_html',
              'venv.lib.python3.5.site-packages.docutils.writers.pep_html',
              'venv.lib.python3.5.site-packages.docutils.writers.html4css1',
              'venv.lib.python3.5.site-packages.docutils.writers.html5_polyglot',
              'venv.lib.python3.5.site-packages.docutils.languages',
              'venv.lib.python3.5.site-packages.docutils.transforms', 'venv.lib.python3.5.site-packages.pygments',
              'venv.lib.python3.5.site-packages.pygments.lexers', 'venv.lib.python3.5.site-packages.pygments.styles',
              'venv.lib.python3.5.site-packages.pygments.filters',
              'venv.lib.python3.5.site-packages.pygments.formatters', 'venv.lib.python3.5.site-packages.requests',
              'venv.lib.python3.5.site-packages.requests.packages',
              'venv.lib.python3.5.site-packages.requests.packages.idna',
              'venv.lib.python3.5.site-packages.requests.packages.chardet',
              'venv.lib.python3.5.site-packages.requests.packages.urllib3',
              'venv.lib.python3.5.site-packages.requests.packages.urllib3.util',
              'venv.lib.python3.5.site-packages.requests.packages.urllib3.contrib',
              'venv.lib.python3.5.site-packages.requests.packages.urllib3.packages',
              'venv.lib.python3.5.site-packages.requests.packages.urllib3.packages.backports',
              'venv.lib.python3.5.site-packages.requests.packages.urllib3.packages.ssl_match_hostname',
              'venv.lib.python3.5.site-packages.werkzeug', 'venv.lib.python3.5.site-packages.werkzeug.debug',
              'venv.lib.python3.5.site-packages.werkzeug.contrib', 'venv.lib.python3.5.site-packages.alabaster',
              'venv.lib.python3.5.site-packages.flask_wtf', 'venv.lib.python3.5.site-packages.flask_wtf.recaptcha',
              'venv.lib.python3.5.site-packages.imagesize', 'venv.lib.python3.5.site-packages.pycparser',
              'venv.lib.python3.5.site-packages.pycparser.ply', 'venv.lib.python3.5.site-packages.markupsafe',
              'venv.lib.python3.5.site-packages.setuptools', 'venv.lib.python3.5.site-packages.setuptools.extern',
              'venv.lib.python3.5.site-packages.setuptools.command', 'venv.lib.python3.5.site-packages.sqlalchemy',
              'venv.lib.python3.5.site-packages.sqlalchemy.ext',
              'venv.lib.python3.5.site-packages.sqlalchemy.ext.declarative',
              'venv.lib.python3.5.site-packages.sqlalchemy.orm', 'venv.lib.python3.5.site-packages.sqlalchemy.sql',
              'venv.lib.python3.5.site-packages.sqlalchemy.util', 'venv.lib.python3.5.site-packages.sqlalchemy.event',
              'venv.lib.python3.5.site-packages.sqlalchemy.engine',
              'venv.lib.python3.5.site-packages.sqlalchemy.testing',
              'venv.lib.python3.5.site-packages.sqlalchemy.testing.suite',
              'venv.lib.python3.5.site-packages.sqlalchemy.testing.plugin',
              'venv.lib.python3.5.site-packages.sqlalchemy.dialects',
              'venv.lib.python3.5.site-packages.sqlalchemy.dialects.mssql',
              'venv.lib.python3.5.site-packages.sqlalchemy.dialects.mysql',
              'venv.lib.python3.5.site-packages.sqlalchemy.dialects.oracle',
              'venv.lib.python3.5.site-packages.sqlalchemy.dialects.sqlite',
              'venv.lib.python3.5.site-packages.sqlalchemy.dialects.sybase',
              'venv.lib.python3.5.site-packages.sqlalchemy.dialects.firebird',
              'venv.lib.python3.5.site-packages.sqlalchemy.dialects.postgresql',
              'venv.lib.python3.5.site-packages.sqlalchemy.databases',
              'venv.lib.python3.5.site-packages.sqlalchemy.connectors', 'venv.lib.python3.5.site-packages.flask_login',
              'venv.lib.python3.5.site-packages.flask_script', 'venv.lib.python3.5.site-packages.flask_migrate',
              'venv.lib.python3.5.site-packages.pkg_resources', 'venv.lib.python3.5.site-packages.pkg_resources.extern',
              'venv.lib.python3.5.site-packages.pkg_resources._vendor',
              'venv.lib.python3.5.site-packages.pkg_resources._vendor.packaging',
              'venv.lib.python3.5.site-packages.snowballstemmer', 'venv.lib.python3.5.site-packages.flask_sqlalchemy',
              'venv.lib64.python3.5.site-packages.pip', 'venv.lib64.python3.5.site-packages.pip.req',
              'venv.lib64.python3.5.site-packages.pip.vcs', 'venv.lib64.python3.5.site-packages.pip.utils',
              'venv.lib64.python3.5.site-packages.pip.compat', 'venv.lib64.python3.5.site-packages.pip.models',
              'venv.lib64.python3.5.site-packages.pip._vendor',
              'venv.lib64.python3.5.site-packages.pip._vendor.distlib',
              'venv.lib64.python3.5.site-packages.pip._vendor.distlib._backport',
              'venv.lib64.python3.5.site-packages.pip._vendor.colorama',
              'venv.lib64.python3.5.site-packages.pip._vendor.html5lib',
              'venv.lib64.python3.5.site-packages.pip._vendor.html5lib._trie',
              'venv.lib64.python3.5.site-packages.pip._vendor.html5lib.filters',
              'venv.lib64.python3.5.site-packages.pip._vendor.html5lib.treewalkers',
              'venv.lib64.python3.5.site-packages.pip._vendor.html5lib.treeadapters',
              'venv.lib64.python3.5.site-packages.pip._vendor.html5lib.treebuilders',
              'venv.lib64.python3.5.site-packages.pip._vendor.lockfile',
              'venv.lib64.python3.5.site-packages.pip._vendor.progress',
              'venv.lib64.python3.5.site-packages.pip._vendor.requests',
              'venv.lib64.python3.5.site-packages.pip._vendor.requests.packages',
              'venv.lib64.python3.5.site-packages.pip._vendor.requests.packages.chardet',
              'venv.lib64.python3.5.site-packages.pip._vendor.requests.packages.urllib3',
              'venv.lib64.python3.5.site-packages.pip._vendor.requests.packages.urllib3.util',
              'venv.lib64.python3.5.site-packages.pip._vendor.requests.packages.urllib3.contrib',
              'venv.lib64.python3.5.site-packages.pip._vendor.requests.packages.urllib3.packages',
              'venv.lib64.python3.5.site-packages.pip._vendor.requests.packages.urllib3.packages.ssl_match_hostname',
              'venv.lib64.python3.5.site-packages.pip._vendor.packaging',
              'venv.lib64.python3.5.site-packages.pip._vendor.cachecontrol',
              'venv.lib64.python3.5.site-packages.pip._vendor.cachecontrol.caches',
              'venv.lib64.python3.5.site-packages.pip._vendor.webencodings',
              'venv.lib64.python3.5.site-packages.pip._vendor.pkg_resources',
              'venv.lib64.python3.5.site-packages.pip.commands', 'venv.lib64.python3.5.site-packages.pip.operations',
              'venv.lib64.python3.5.site-packages.cffi', 'venv.lib64.python3.5.site-packages.mako',
              'venv.lib64.python3.5.site-packages.mako.ext', 'venv.lib64.python3.5.site-packages.pytz',
              'venv.lib64.python3.5.site-packages.babel', 'venv.lib64.python3.5.site-packages.babel.messages',
              'venv.lib64.python3.5.site-packages.babel.localtime', 'venv.lib64.python3.5.site-packages.click',
              'venv.lib64.python3.5.site-packages.flask', 'venv.lib64.python3.5.site-packages.flask.ext',
              'venv.lib64.python3.5.site-packages.bcrypt', 'venv.lib64.python3.5.site-packages.jinja2',
              'venv.lib64.python3.5.site-packages.sphinx', 'venv.lib64.python3.5.site-packages.sphinx.ext',
              'venv.lib64.python3.5.site-packages.sphinx.ext.napoleon',
              'venv.lib64.python3.5.site-packages.sphinx.ext.autosummary',
              'venv.lib64.python3.5.site-packages.sphinx.util', 'venv.lib64.python3.5.site-packages.sphinx.locale',
              'venv.lib64.python3.5.site-packages.sphinx.pycode',
              'venv.lib64.python3.5.site-packages.sphinx.pycode.pgen2',
              'venv.lib64.python3.5.site-packages.sphinx.search', 'venv.lib64.python3.5.site-packages.sphinx.domains',
              'venv.lib64.python3.5.site-packages.sphinx.writers', 'venv.lib64.python3.5.site-packages.sphinx.builders',
              'venv.lib64.python3.5.site-packages.sphinx.directives',
              'venv.lib64.python3.5.site-packages.sphinx.transforms',
              'venv.lib64.python3.5.site-packages.sphinx.websupport',
              'venv.lib64.python3.5.site-packages.sphinx.websupport.search',
              'venv.lib64.python3.5.site-packages.sphinx.websupport.storage',
              'venv.lib64.python3.5.site-packages.sphinx.environment',
              'venv.lib64.python3.5.site-packages.sphinx.environment.managers',
              'venv.lib64.python3.5.site-packages.alembic', 'venv.lib64.python3.5.site-packages.alembic.ddl',
              'venv.lib64.python3.5.site-packages.alembic.util', 'venv.lib64.python3.5.site-packages.alembic.script',
              'venv.lib64.python3.5.site-packages.alembic.runtime',
              'venv.lib64.python3.5.site-packages.alembic.testing',
              'venv.lib64.python3.5.site-packages.alembic.testing.plugin',
              'venv.lib64.python3.5.site-packages.alembic.operations',
              'venv.lib64.python3.5.site-packages.alembic.autogenerate', 'venv.lib64.python3.5.site-packages.wtforms',
              'venv.lib64.python3.5.site-packages.wtforms.ext', 'venv.lib64.python3.5.site-packages.wtforms.ext.csrf',
              'venv.lib64.python3.5.site-packages.wtforms.ext.i18n',
              'venv.lib64.python3.5.site-packages.wtforms.ext.django',
              'venv.lib64.python3.5.site-packages.wtforms.ext.django.templatetags',
              'venv.lib64.python3.5.site-packages.wtforms.ext.dateutil',
              'venv.lib64.python3.5.site-packages.wtforms.ext.appengine',
              'venv.lib64.python3.5.site-packages.wtforms.ext.sqlalchemy',
              'venv.lib64.python3.5.site-packages.wtforms.csrf', 'venv.lib64.python3.5.site-packages.wtforms.fields',
              'venv.lib64.python3.5.site-packages.wtforms.widgets', 'venv.lib64.python3.5.site-packages.docutils',
              'venv.lib64.python3.5.site-packages.docutils.utils',
              'venv.lib64.python3.5.site-packages.docutils.utils.math',
              'venv.lib64.python3.5.site-packages.docutils.parsers',
              'venv.lib64.python3.5.site-packages.docutils.parsers.rst',
              'venv.lib64.python3.5.site-packages.docutils.parsers.rst.languages',
              'venv.lib64.python3.5.site-packages.docutils.parsers.rst.directives',
              'venv.lib64.python3.5.site-packages.docutils.readers',
              'venv.lib64.python3.5.site-packages.docutils.writers',
              'venv.lib64.python3.5.site-packages.docutils.writers.xetex',
              'venv.lib64.python3.5.site-packages.docutils.writers.latex2e',
              'venv.lib64.python3.5.site-packages.docutils.writers.odf_odt',
              'venv.lib64.python3.5.site-packages.docutils.writers.s5_html',
              'venv.lib64.python3.5.site-packages.docutils.writers.pep_html',
              'venv.lib64.python3.5.site-packages.docutils.writers.html4css1',
              'venv.lib64.python3.5.site-packages.docutils.writers.html5_polyglot',
              'venv.lib64.python3.5.site-packages.docutils.languages',
              'venv.lib64.python3.5.site-packages.docutils.transforms', 'venv.lib64.python3.5.site-packages.pygments',
              'venv.lib64.python3.5.site-packages.pygments.lexers',
              'venv.lib64.python3.5.site-packages.pygments.styles',
              'venv.lib64.python3.5.site-packages.pygments.filters',
              'venv.lib64.python3.5.site-packages.pygments.formatters', 'venv.lib64.python3.5.site-packages.requests',
              'venv.lib64.python3.5.site-packages.requests.packages',
              'venv.lib64.python3.5.site-packages.requests.packages.idna',
              'venv.lib64.python3.5.site-packages.requests.packages.chardet',
              'venv.lib64.python3.5.site-packages.requests.packages.urllib3',
              'venv.lib64.python3.5.site-packages.requests.packages.urllib3.util',
              'venv.lib64.python3.5.site-packages.requests.packages.urllib3.contrib',
              'venv.lib64.python3.5.site-packages.requests.packages.urllib3.packages',
              'venv.lib64.python3.5.site-packages.requests.packages.urllib3.packages.backports',
              'venv.lib64.python3.5.site-packages.requests.packages.urllib3.packages.ssl_match_hostname',
              'venv.lib64.python3.5.site-packages.werkzeug', 'venv.lib64.python3.5.site-packages.werkzeug.debug',
              'venv.lib64.python3.5.site-packages.werkzeug.contrib', 'venv.lib64.python3.5.site-packages.alabaster',
              'venv.lib64.python3.5.site-packages.flask_wtf', 'venv.lib64.python3.5.site-packages.flask_wtf.recaptcha',
              'venv.lib64.python3.5.site-packages.imagesize', 'venv.lib64.python3.5.site-packages.pycparser',
              'venv.lib64.python3.5.site-packages.pycparser.ply', 'venv.lib64.python3.5.site-packages.markupsafe',
              'venv.lib64.python3.5.site-packages.setuptools', 'venv.lib64.python3.5.site-packages.setuptools.extern',
              'venv.lib64.python3.5.site-packages.setuptools.command', 'venv.lib64.python3.5.site-packages.sqlalchemy',
              'venv.lib64.python3.5.site-packages.sqlalchemy.ext',
              'venv.lib64.python3.5.site-packages.sqlalchemy.ext.declarative',
              'venv.lib64.python3.5.site-packages.sqlalchemy.orm', 'venv.lib64.python3.5.site-packages.sqlalchemy.sql',
              'venv.lib64.python3.5.site-packages.sqlalchemy.util',
              'venv.lib64.python3.5.site-packages.sqlalchemy.event',
              'venv.lib64.python3.5.site-packages.sqlalchemy.engine',
              'venv.lib64.python3.5.site-packages.sqlalchemy.testing',
              'venv.lib64.python3.5.site-packages.sqlalchemy.testing.suite',
              'venv.lib64.python3.5.site-packages.sqlalchemy.testing.plugin',
              'venv.lib64.python3.5.site-packages.sqlalchemy.dialects',
              'venv.lib64.python3.5.site-packages.sqlalchemy.dialects.mssql',
              'venv.lib64.python3.5.site-packages.sqlalchemy.dialects.mysql',
              'venv.lib64.python3.5.site-packages.sqlalchemy.dialects.oracle',
              'venv.lib64.python3.5.site-packages.sqlalchemy.dialects.sqlite',
              'venv.lib64.python3.5.site-packages.sqlalchemy.dialects.sybase',
              'venv.lib64.python3.5.site-packages.sqlalchemy.dialects.firebird',
              'venv.lib64.python3.5.site-packages.sqlalchemy.dialects.postgresql',
              'venv.lib64.python3.5.site-packages.sqlalchemy.databases',
              'venv.lib64.python3.5.site-packages.sqlalchemy.connectors',
              'venv.lib64.python3.5.site-packages.flask_login', 'venv.lib64.python3.5.site-packages.flask_script',
              'venv.lib64.python3.5.site-packages.flask_migrate', 'venv.lib64.python3.5.site-packages.pkg_resources',
              'venv.lib64.python3.5.site-packages.pkg_resources.extern',
              'venv.lib64.python3.5.site-packages.pkg_resources._vendor',
              'venv.lib64.python3.5.site-packages.pkg_resources._vendor.packaging',
              'venv.lib64.python3.5.site-packages.snowballstemmer',
              'venv.lib64.python3.5.site-packages.flask_sqlalchemy', 'tests', 'config',
              'provenv.lib.python3.5.distutils', 'provenv.lib.python3.5.encodings', 'provenv.lib.python3.5.importlib',
              'provenv.lib.python3.5.collections', 'provenv.lib.python3.5.site-packages.pip',
              'provenv.lib.python3.5.site-packages.pip.req', 'provenv.lib.python3.5.site-packages.pip.vcs',
              'provenv.lib.python3.5.site-packages.pip.utils', 'provenv.lib.python3.5.site-packages.pip.compat',
              'provenv.lib.python3.5.site-packages.pip.models', 'provenv.lib.python3.5.site-packages.pip._vendor',
              'provenv.lib.python3.5.site-packages.pip._vendor.distlib',
              'provenv.lib.python3.5.site-packages.pip._vendor.distlib._backport',
              'provenv.lib.python3.5.site-packages.pip._vendor.colorama',
              'provenv.lib.python3.5.site-packages.pip._vendor.html5lib',
              'provenv.lib.python3.5.site-packages.pip._vendor.html5lib._trie',
              'provenv.lib.python3.5.site-packages.pip._vendor.html5lib.filters',
              'provenv.lib.python3.5.site-packages.pip._vendor.html5lib.treewalkers',
              'provenv.lib.python3.5.site-packages.pip._vendor.html5lib.treeadapters',
              'provenv.lib.python3.5.site-packages.pip._vendor.html5lib.treebuilders',
              'provenv.lib.python3.5.site-packages.pip._vendor.lockfile',
              'provenv.lib.python3.5.site-packages.pip._vendor.progress',
              'provenv.lib.python3.5.site-packages.pip._vendor.requests',
              'provenv.lib.python3.5.site-packages.pip._vendor.requests.packages',
              'provenv.lib.python3.5.site-packages.pip._vendor.requests.packages.chardet',
              'provenv.lib.python3.5.site-packages.pip._vendor.requests.packages.urllib3',
              'provenv.lib.python3.5.site-packages.pip._vendor.requests.packages.urllib3.util',
              'provenv.lib.python3.5.site-packages.pip._vendor.requests.packages.urllib3.contrib',
              'provenv.lib.python3.5.site-packages.pip._vendor.requests.packages.urllib3.packages',
              'provenv.lib.python3.5.site-packages.pip._vendor.requests.packages.urllib3.packages.ssl_match_hostname',
              'provenv.lib.python3.5.site-packages.pip._vendor.packaging',
              'provenv.lib.python3.5.site-packages.pip._vendor.cachecontrol',
              'provenv.lib.python3.5.site-packages.pip._vendor.cachecontrol.caches',
              'provenv.lib.python3.5.site-packages.pip._vendor.webencodings',
              'provenv.lib.python3.5.site-packages.pip._vendor.pkg_resources',
              'provenv.lib.python3.5.site-packages.pip.commands', 'provenv.lib.python3.5.site-packages.pip.operations',
              'provenv.lib.python3.5.site-packages.cffi', 'provenv.lib.python3.5.site-packages.click',
              'provenv.lib.python3.5.site-packages.flask', 'provenv.lib.python3.5.site-packages.flask.ext',
              'provenv.lib.python3.5.site-packages.wheel', 'provenv.lib.python3.5.site-packages.wheel.test',
              'provenv.lib.python3.5.site-packages.wheel.test.simple.dist.simpledist',
              'provenv.lib.python3.5.site-packages.wheel.test.complex-dist.complexdist',
              'provenv.lib.python3.5.site-packages.wheel.tool', 'provenv.lib.python3.5.site-packages.wheel.signatures',
              'provenv.lib.python3.5.site-packages.bcrypt', 'provenv.lib.python3.5.site-packages.jinja2',
              'provenv.lib.python3.5.site-packages.wtforms', 'provenv.lib.python3.5.site-packages.wtforms.ext',
              'provenv.lib.python3.5.site-packages.wtforms.ext.csrf',
              'provenv.lib.python3.5.site-packages.wtforms.ext.i18n',
              'provenv.lib.python3.5.site-packages.wtforms.ext.django',
              'provenv.lib.python3.5.site-packages.wtforms.ext.django.templatetags',
              'provenv.lib.python3.5.site-packages.wtforms.ext.dateutil',
              'provenv.lib.python3.5.site-packages.wtforms.ext.appengine',
              'provenv.lib.python3.5.site-packages.wtforms.ext.sqlalchemy',
              'provenv.lib.python3.5.site-packages.wtforms.csrf', 'provenv.lib.python3.5.site-packages.wtforms.fields',
              'provenv.lib.python3.5.site-packages.wtforms.widgets', 'provenv.lib.python3.5.site-packages.werkzeug',
              'provenv.lib.python3.5.site-packages.werkzeug.debug',
              'provenv.lib.python3.5.site-packages.werkzeug.contrib', 'provenv.lib.python3.5.site-packages.flask_wtf',
              'provenv.lib.python3.5.site-packages.flask_wtf.recaptcha',
              'provenv.lib.python3.5.site-packages.packaging', 'provenv.lib.python3.5.site-packages.pycparser',
              'provenv.lib.python3.5.site-packages.pycparser.ply', 'provenv.lib.python3.5.site-packages.markupsafe',
              'provenv.lib.python3.5.site-packages.setuptools',
              'provenv.lib.python3.5.site-packages.setuptools.command',
              'provenv.lib.python3.5.site-packages.sqlalchemy', 'provenv.lib.python3.5.site-packages.sqlalchemy.ext',
              'provenv.lib.python3.5.site-packages.sqlalchemy.ext.declarative',
              'provenv.lib.python3.5.site-packages.sqlalchemy.orm',
              'provenv.lib.python3.5.site-packages.sqlalchemy.sql',
              'provenv.lib.python3.5.site-packages.sqlalchemy.util',
              'provenv.lib.python3.5.site-packages.sqlalchemy.event',
              'provenv.lib.python3.5.site-packages.sqlalchemy.engine',
              'provenv.lib.python3.5.site-packages.sqlalchemy.testing',
              'provenv.lib.python3.5.site-packages.sqlalchemy.testing.suite',
              'provenv.lib.python3.5.site-packages.sqlalchemy.testing.plugin',
              'provenv.lib.python3.5.site-packages.sqlalchemy.dialects',
              'provenv.lib.python3.5.site-packages.sqlalchemy.dialects.mssql',
              'provenv.lib.python3.5.site-packages.sqlalchemy.dialects.mysql',
              'provenv.lib.python3.5.site-packages.sqlalchemy.dialects.oracle',
              'provenv.lib.python3.5.site-packages.sqlalchemy.dialects.sqlite',
              'provenv.lib.python3.5.site-packages.sqlalchemy.dialects.sybase',
              'provenv.lib.python3.5.site-packages.sqlalchemy.dialects.firebird',
              'provenv.lib.python3.5.site-packages.sqlalchemy.dialects.postgresql',
              'provenv.lib.python3.5.site-packages.sqlalchemy.databases',
              'provenv.lib.python3.5.site-packages.sqlalchemy.connectors',
              'provenv.lib.python3.5.site-packages.flask_login', 'provenv.lib.python3.5.site-packages.pkg_resources',
              'provenv.lib.python3.5.site-packages.flask_sqlalchemy', 'WhatAClass'],
    url='',
    license='',
    author='Javier Martinez',
    author_email='javyermartinez@gmail.com',
    description='Simple web app to act as a gui'
)
