from setuptools import setup

setup(
    name='WhatAClass',
    packages=['WhatAClass'],
    include_package_data=True,
    install_requires=[       
        'alembic',
        'bcrypt',
        'Flask',
        'Flask-Babel',
        'Flask-Bcrypt',
        'Flask-Login',
        'Flask-SQLAlchemy',
        'Flask-WTF',
        'itsdangerous',
        'Jinja2',
        'psycopg2',
        'SQLAlchemy',
        'Werkzeug',
        'WTForms',
    ],
    setup_requires=[
        'pytest-runner',
    ],
    tests_require=[
        'pytest',
    ],
)